/** Header for generated product files. Keep the marker greppable. */
export function provenanceHeader(sha: string): string {
  return `// generated-from: ${sha}\n// regenerated by /curriculum-refinery products — edit the book spec, not this file\n`;
}

/** Accepts `//`, `/*`, or `<!--` comment forms anywhere in the first match. */
export function parseProvenance(fileText: string): string | null {
  const m = fileText.match(/generated-from: ([0-9a-f]{7,40})/);
  return m ? m[1] : null;
}
