/**
 * Program Blueprint Task 5 — coach-side distribution notification +
 * prescribed-session badge payload. See "Distribution" § "Coach
 * notification" and "The coach seam" in
 * docs/superpowers/specs/2026-07-10-program-blueprint-design.md.
 *
 * Distributes a real sequence (mirrors the fixture pattern in
 * tests/api/admin/blueprint-attach.test.ts) onto a season with TWO teams:
 * team A coached by the seeded coach fixture, team B coached by the admin
 * fixture account (teams.coachUserId is just an FK — assigning the admin
 * user makes it a legitimate "second coach" for this attachment without
 * needing a dedicated second coach login). Both teams' sessions are
 * generated by the SAME attach call and therefore share one
 * sequence_attachments row — this lets (d) prove the nudge endpoint scopes
 * sessionCount/groupLabel to the CALLER's own team(s) under that shared
 * attachment, not the whole distribution run.
 */
import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { inArray } from "drizzle-orm";
import { getDb } from "@/lib/db";
import { sessionPlans } from "@/lib/db/schema";
import { groupNoun } from "@/lib/programs/group-noun";
import {
  apiFetch,
  expectJson,
  getAdminCookie,
  getCoachCookie,
  getParentCookie,
  testSlug,
  resetCookies,
} from "../setup/test-helpers";

const SEQUENCES_ENDPOINT = "/api/admin/curriculum/sequences";

describe("Program Blueprint — coach program-plan nudge + prescribed badge payload", () => {
  let adminCookie: string;
  let coachCookie: string;
  let parentCookie: string;
  let adminUserId: string;
  let coachUserId: string;
  let orgASportId: string;
  let programId: string;
  let expectedNoun: string;
  let developmentStageId: string | null = null;

  let templateId: string | null = null;
  let sequenceId: string | null = null;
  let seasonId: string;
  let seasonName: string;
  let teamAId: string; // coached by the seeded coach fixture
  let teamAName: string;
  let teamBId: string; // coached by the admin fixture (stand-in "second coach")
  let teamBName: string;

  let attachmentId: string | null = null;
  const recurrence = {
    weekday: 6,
    startDate: "2026-11-07",
    timeOfDay: "09:00",
    count: 2,
  };

  let coachCreatedSessionId: string | null = null;
  let earliestDateExpected: string;

  beforeAll(async () => {
    adminCookie = await getAdminCookie();
    coachCookie = await getCoachCookie();
    parentCookie = await getParentCookie();

    const adminMe = await expectJson(
      await apiFetch("/api/auth/me", { method: "GET", cookie: adminCookie }),
      200,
    );
    adminUserId = adminMe.user.id;
    const coachMe = await expectJson(
      await apiFetch("/api/auth/me", { method: "GET", cookie: coachCookie }),
      200,
    );
    coachUserId = coachMe.user.id;

    const sportsRes = await apiFetch("/api/admin/sports", {
      method: "GET",
      cookie: adminCookie,
    });
    orgASportId = (await expectJson(sportsRes, 200)).sports[0].id;

    const programsJson = await expectJson(
      await apiFetch("/api/admin/programs", { method: "GET", cookie: adminCookie }),
      200,
    );
    programId = programsJson.programs[0].id;
    expectedNoun = groupNoun(programsJson.programs[0].programType);

    const tplListRes = await apiFetch("/api/admin/curriculum/templates", {
      method: "GET",
      cookie: adminCookie,
    });
    const tplListJson = await expectJson(tplListRes, 200);
    const developmentStage = (tplListJson.stages ?? []).find(
      (s: any) => s.slug === "development",
    );
    developmentStageId = developmentStage?.id ?? null;
    if (!developmentStageId) return; // runtime skip: no development_stages seeded

    // Clean template — no flagged skills, so distribution never hits the
    // safety block tier regardless of the season's age band.
    const tplRes = await apiFetch("/api/admin/curriculum/templates", {
      method: "POST",
      cookie: adminCookie,
      body: JSON.stringify({
        sportId: orgASportId,
        stageId: developmentStageId,
        name: testSlug("program-plan-tpl"),
        totalDurationMinutes: 45,
        structure: [{ name: "Passing warmup", type: "technical", durationMinutes: 20 }],
      }),
    });
    templateId = (await expectJson(tplRes, 201)).template.id;

    const seqRes = await apiFetch(SEQUENCES_ENDPOINT, {
      method: "POST",
      cookie: adminCookie,
      body: JSON.stringify({
        sportId: orgASportId,
        developmentStageId,
        programType: programsJson.programs[0].programType,
        name: testSlug("program-plan-sequence"),
      }),
    });
    sequenceId = (await expectJson(seqRes, 201)).sequence.id;
    await expectJson(
      await apiFetch(`${SEQUENCES_ENDPOINT}/${sequenceId}/entries`, {
        method: "PUT",
        cookie: adminCookie,
        body: JSON.stringify({
          entries: [{ templateId }, { templateId }],
        }),
      }),
      200,
    );

    seasonName = testSlug("Program Plan Season");
    const seasonJson = await expectJson(
      await apiFetch("/api/admin/seasons", {
        method: "POST",
        cookie: adminCookie,
        body: JSON.stringify({
          programId,
          name: seasonName,
          slug: testSlug("program-plan-season"),
          startDate: "2026-09-01",
          endDate: "2026-12-15",
          priceCents: 15000,
          status: "draft",
          minAge: 12,
          maxAge: 14,
        }),
      }),
      201,
    );
    seasonId = seasonJson.season.id;
    seasonName = seasonJson.season.name;

    teamAName = testSlug("program-plan-team-a");
    const teamAJson = await expectJson(
      await apiFetch("/api/admin/teams", {
        method: "POST",
        cookie: adminCookie,
        body: JSON.stringify({
          seasonId,
          name: teamAName,
          coachUserId,
        }),
      }),
      201,
    );
    teamAId = teamAJson.team.id;

    teamBName = testSlug("program-plan-team-b");
    const teamBJson = await expectJson(
      await apiFetch("/api/admin/teams", {
        method: "POST",
        cookie: adminCookie,
        body: JSON.stringify({
          seasonId,
          name: teamBName,
          coachUserId: adminUserId,
        }),
      }),
      201,
    );
    teamBId = teamBJson.team.id;

    const attachRes = await apiFetch(`${SEQUENCES_ENDPOINT}/${sequenceId}/attach`, {
      method: "POST",
      cookie: adminCookie,
      body: JSON.stringify({ seasonId, ...recurrence }),
    });
    const attachJson = await expectJson(attachRes, 200);
    attachmentId = attachJson.attachmentId;
    expect(attachmentId).toBeTruthy();
    const teamAResult = attachJson.results.find((r: any) => r.teamId === teamAId);
    expect(teamAResult.created).toBe(2);
    const teamBResult = attachJson.results.find((r: any) => r.teamId === teamBId);
    expect(teamBResult.created).toBe(2);

    // Capture the actual earliest scheduledDate the attach run produced for
    // team A (BEFORE the coach-created session below exists), rather than
    // hardcoding a literal — avoids coupling this test to the org's
    // timezone/DST handling inside generatePracticeDates.
    const teamASessionsJson = await expectJson(
      await apiFetch(`/api/coach/sessions?teamId=${teamAId}`, {
        method: "GET",
        cookie: coachCookie,
      }),
      200,
    );
    expect(teamASessionsJson.sessions).toHaveLength(2);
    earliestDateExpected = [...teamASessionsJson.sessions]
      .map((s: any) => s.scheduledDate)
      .sort()[0];

    // A coach-created (non-prescribed) session on team A, for the badge
    // payload's null case in (c).
    const createdRes = await apiFetch("/api/coach/sessions", {
      method: "POST",
      cookie: coachCookie,
      body: JSON.stringify({
        teamId: teamAId,
        title: "Coach-created session",
        scheduledDate: "2026-11-21T14:00:00.000Z",
        durationMinutes: 60,
        status: "planned",
      }),
    });
    coachCreatedSessionId = (await expectJson(createdRes, 201)).session.id;
  });

  afterAll(async () => {
    const db = getDb();
    const teamIds = [teamAId, teamBId].filter((id): id is string => Boolean(id));
    if (teamIds.length > 0) {
      await db.delete(sessionPlans).where(inArray(sessionPlans.teamId, teamIds));
    }
    if (sequenceId) {
      // Cascades the sequence_attachments row (sequenceId FK onDelete:
      // cascade) — session_plans rows are already gone above.
      await apiFetch(`${SEQUENCES_ENDPOINT}/${sequenceId}`, {
        method: "DELETE",
        cookie: adminCookie,
      });
    }
    if (templateId) {
      await apiFetch(`/api/admin/curriculum/templates/${templateId}`, {
        method: "DELETE",
        cookie: adminCookie,
      });
    }
    resetCookies();
  });

  it("(a) lists the distribution on the coach's nudge with correct sessionCount/noun/distributor, scoped to their own team", async () => {
    if (!sequenceId) return; // runtime skip: no development_stages seeded

    const json = await expectJson(
      await apiFetch("/api/coach/program-plan/nudge", {
        method: "GET",
        cookie: coachCookie,
      }),
      200,
    );
    expect(Array.isArray(json.pending)).toBe(true);
    const entry = json.pending.find((p: any) => p.attachmentId === attachmentId);
    expect(entry).toBeDefined();
    expect(entry.seasonName).toBe(seasonName);
    expect(entry.groupLabel).toBe(teamAName);
    expect(entry.noun).toBe(expectedNoun);
    expect(entry.sessionCount).toBe(2); // team A's sessions only, not team B's
    expect(entry.distributorFirstName).toBe("Test"); // seeded admin fixture's firstName
    expect(entry.earliestDate).toBe(earliestDateExpected);
  });

  it("(b) is forbidden for a parent", async () => {
    const res = await apiFetch("/api/coach/program-plan/nudge", {
      method: "GET",
      cookie: parentCookie,
    });
    expect(res.status).toBe(403);
  });

  it("is unauthorized without a session cookie", async () => {
    const res = await apiFetch("/api/coach/program-plan/nudge", { method: "GET" });
    expect(res.status).toBe(401);
  });

  it("(c) GET /api/coach/sessions shows prescribed{} on distributed sessions and null on a coach-created one", async () => {
    if (!sequenceId) return;

    const json = await expectJson(
      await apiFetch(`/api/coach/sessions?teamId=${teamAId}`, {
        method: "GET",
        cookie: coachCookie,
      }),
      200,
    );
    const distributed = json.sessions.filter(
      (s: any) => s.id !== coachCreatedSessionId,
    );
    expect(distributed.length).toBe(2);
    for (const s of distributed) {
      expect(s.prescribed).toEqual({
        attachmentId,
        distributorFirstName: "Test",
      });
    }

    const coachCreated = json.sessions.find(
      (s: any) => s.id === coachCreatedSessionId,
    );
    expect(coachCreated).toBeDefined();
    expect(coachCreated.prescribed).toBeNull();

    // Same shape on the single-session detail endpoint.
    const detailJson = await expectJson(
      await apiFetch(`/api/coach/sessions/${distributed[0].id}`, {
        method: "GET",
        cookie: coachCookie,
      }),
      200,
    );
    expect(detailJson.session.prescribed).toEqual({
      attachmentId,
      distributorFirstName: "Test",
    });

    const coachCreatedDetailJson = await expectJson(
      await apiFetch(`/api/coach/sessions/${coachCreatedSessionId}`, {
        method: "GET",
        cookie: coachCookie,
      }),
      200,
    );
    expect(coachCreatedDetailJson.session.prescribed).toBeNull();
  });

  it("(d) scopes the nudge to the caller's own team: the admin (coach of team B under the SAME attachment) sees team B's label/count, never team A's", async () => {
    if (!sequenceId) return;

    const json = await expectJson(
      await apiFetch("/api/coach/program-plan/nudge", {
        method: "GET",
        cookie: adminCookie,
      }),
      200,
    );
    const entry = json.pending.find((p: any) => p.attachmentId === attachmentId);
    expect(entry).toBeDefined();
    expect(entry.groupLabel).toBe(teamBName);
    expect(entry.groupLabel).not.toBe(teamAName);
    expect(entry.sessionCount).toBe(2); // team B's own sessions only
  });
});
